# Generated by Django 3.0.5 on 2020-04-26 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=255)),
                ('project_directions', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('requirements', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost', models.CharField(max_length=255)),
                ('link_to_documents', models.CharField(max_length=255)),
                ('link_to_official', models.CharField(max_length=255)),
                ('contacts', models.CharField(max_length=255)),
                ('link_to_npa', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.City')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Grade')),
                ('participants', models.ManyToManyField(to='articles.Participant')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Source')),
            ],
        ),
    ]
