# Generated by Django 3.0.5 on 2020-04-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cost_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='cost_min',
            field=models.IntegerField(default=0),
        ),
    ]
