# Generated by Django 3.0.5 on 2020-04-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('PUB', 'Опубликовано'), ('EDT', 'Редактируется'), ('DEL', 'Удалено')], default='EDT', max_length=3),
        ),
    ]
