# Generated by Django 3.0.5 on 2020-04-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200426_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='participants',
            field=models.ManyToManyField(to='articles.Participant'),
        ),
    ]
