# Generated by Django 3.0.5 on 2020-04-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200428_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='upon_request',
            field=models.BooleanField(default=False),
        ),
    ]
